---
name: Continuous Integration

"on":
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  ci:
    uses: sbaerlocher/.github/.github/workflows/ci-js.yml@2026-05-07
    with:
      package-manager: "npm"
      enable-codecov: true
      enable-sarif-upload: true
    secrets: inherit

  status:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs: [ci]
    if: always()
    steps:
      - name: Check results
        env:
          CI_RESULT: ${{ needs.ci.result }}
        run: |
          if [[ "$CI_RESULT" != "success" ]]; then
            echo "CI failed"
            exit 1
          fi
          echo "All checks passed"
