name: publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      npm-tag:
        description: 'NPM tag (latest, beta, next)'
        required: false
        default: 'latest'

permissions:
  contents: read
  id-token: write

jobs:
  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run lint

      - name: Build library bundle
        run: npm run build:bundle

      - name: Verify package contents
        run: npm pack --dry-run

      - name: Publish to npm
        run: |
          if [ "${{ github.event.inputs.npm-tag }}" != "" ]; then
            npm publish --tag ${{ github.event.inputs.npm-tag }} --provenance --access public
          else
            npm publish --provenance --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
